In [1]:
import numpy as np

In [3]:
def data_generator(n_samples=10000, fr = 0.1, seed=37):
    np.random.seed(seed)
    nneg = int(fr*n_samples)
    npos = n_samples - nneg
    
    ypred_pos = np.round(np.clip(np.random.normal(0.75, 0.2, npos), 0, 1), 3)
    ypred_neg = np.round(np.clip(np.random.normal(0.25, 0.2, nneg), 0, 1), 3)
    
    output = np.vstack((
        np.c_[ypred_pos, np.ones(npos)],
        np.c_[ypred_neg, np.zeros(nneg)]
    ))
    np.random.shuffle(output)
    return output

data = data_generator()
data

array([[0.519, 1.   ],
       [0.503, 1.   ],
       [0.708, 1.   ],
       ...,
       [0.641, 1.   ],
       [0.962, 1.   ],
       [0.757, 1.   ]])

In [9]:
threshold = 0.5
ypred = (data[:, 0] > threshold).astype(int)
ytrue = data[:, 1]

In [32]:
%%time
tp = np.logical_and(ypred == ytrue, ytrue == 1).sum()
fp = np.logical_and(ypred == 1 - ytrue, ytrue == 0).sum()
tn = np.logical_and(ypred == ytrue, ytrue == 0).sum()
fn = np.logical_and(ypred == 1 - ytrue, ytrue == 1).sum()

mcoff = np.vstack((np.c_[tn, fp], np.c_[fn, tp]))
mcoff

CPU times: total: 0 ns
Wall time: 2 ms


array([[ 897,  103],
       [ 929, 8071]])

In [33]:
%%time
tp = np.logical_and(ypred == ytrue, ytrue == 1).sum()
fp = np.logical_and(ypred != ytrue, ytrue == 0).sum()
tn = np.logical_and(ypred == ytrue, ytrue == 0).sum()
fn = np.logical_and(ypred != ytrue, ytrue == 1).sum()

mcoff = np.vstack((np.c_[tn, fp], np.c_[fn, tp]))
mcoff

CPU times: total: 0 ns
Wall time: 1 ms


array([[ 897,  103],
       [ 929, 8071]])

In [34]:
from sklearn.metrics import confusion_matrix
confusion_matrix(ytrue, ypred)

array([[ 897,  103],
       [ 929, 8071]])

In [40]:
recall = (tp / (tp + fn)).item()
precision = (tp / (tp + fp)).item()
specificity = (tn / (tn + fp)).item()
f1 = 1 / (1/recall + 1/precision)
accuracy = ((tn + tp) / mcoff.sum()).item()

print(f"{recall=}")
print(f"{precision=}")
print(f"{specificity=}")
print(f"{f1=}")
print(f"{accuracy=}")

recall=0.8967777777777778
precision=0.9873990702226572
specificity=0.897
f1=0.469954582508443
accuracy=0.8968
